routes:
  /:
    template: index
  /research/work/:
    template: research
    controller: channel
    filter: tag:zuo-pin
    data: tag.zuo-pin
  /research/essay/:
    template: research-list
    controller: channel
    filter: tag:research-essay
    data: tag.research-essay
  /research/dataset/:
    template: research
    controller: channel
    filter: tag:shu-ju-ji
    data: tag.shu-ju-ji
  /archive/musicgroup/:
    template: archive
    controller: channel
    filter: tag:wen-zhang+tag:yin-le-zu
  /archive/fontgroup/:
    template: archive
    controller: channel
    filter: tag:wen-zhang+tag:zi-ti-zu
  /archive/designgroup/:
    template: archive
    controller: channel
    filter: tag:wen-zhang+tag:she-ji-zu
  /archive/english/:
    template: archive
    controller: channel
    filter: tag:wen-zhang+tag:ying-wen-wen-zhang
collections:
  /research/:
    permalink: /research/{slug}/
    template: research
    filter: tag:yan-jiu
    data: tag.yan-jiu
  /course/:
    permalink: /course/{slug}/
    template: course
    filter: tag:ke-cheng
    data: tag.ke-cheng
  /archive/:
    permalink: /archive/{slug}/
    template: archive
    filter: tag:wen-zhang
    data: tag.wen-zhang
  /people/:
    permalink: /people/{slug}/
    template: people
    filter: tag:ren-yuan
    data: tag.ren-yuan
taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
