routes:
  /:
    template: index
  /research/work/:
    template: research
    controller: channel
    filter: tag:作品
    data: tag.作品
  /research/essay/:
    template: research-list
    controller: channel
    filter: tag:research-essay
    data: tag.research-essay
  /research/dataset/:
    template: research
    controller: channel
    filter: tag:数据集
    data: tag.数据集
  /research/result/:
    template: research-list
    controller: channel
    filter: tag:research-result
    data: tag.research-result 
  /research/resource/:
    template: research-list
    controller: channel
    filter: tag:research-resource
    data: tag.research-resource
  /archive/musicgroup/:
    template: archive
    controller: channel
    filter: tag:文章+tag:音乐组
  /archive/fontgroup/:
    template: archive
    controller: channel
    filter: tag:文章+tag:字体组
  /archive/designgroup/:
    template: archive
    controller: channel
    filter: tag:文章+tag:设计组
  /archive/english/:
    template: archive
    controller: channel
    filter: tag:文章+tag:英文文章
collections:
  /research/:
    permalink: /research/{slug}/
    template: research
    filter: tag:研究
    data: tag.研究
  /course/:
    permalink: /course/{slug}/
    template: course
    filter: tag:课程
    data: tag.课程
  /archive/:
    permalink: /archive/{slug}/
    template: archive
    filter: tag:文章
    data: tag.文章
  /people/:
    permalink: /people/{slug}/
    template: people
    filter: tag:人员
    data: tag.人员
taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
